workflows:
  # Flujo de trabajo para iOS (Firma con Apple ID Gratis)
  ios-workflow:
    name: iOS Workflow (Development)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple_credentials  # Grupo con tu Apple ID
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Configurar firma automática con Apple ID
        script: |
          # Usar firma automática con tu Apple ID
          xcode-project use-profiles --export-options-plist=ios/exportOptions.plist || true
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Crear IPA
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/GuiAppesca-v2.0.0-development.ipa Payload
          rm -rf Payload
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - carolina@email.com
        notify:
          success: true
          failure: true

  # Flujo de trabajo para Android
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - carolina@email.com  # Cambia esto por tu email
        notify:
          success: true
          failure: true

  # Flujo de trabajo para ambas plataformas
  all-platforms-workflow:
    name: Build All Platforms
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - carolina@email.com  # Cambia esto por tu email
        notify:
          success: true
          failure: true

