workflows:
  # Flujo de trabajo para iOS (SIN FIRMAR - Sin contraseñas)
  ios-workflow:
    name: iOS Workflow (Unsigned)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build iOS sin firmar
        script: |
          flutter build ios --release --no-codesign
      - name: Crear IPA sin firmar
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r GuiAppesca-unsigned.ipa Payload
          rm -rf Payload
          mkdir -p build/ios/ipa
          mv GuiAppesca-unsigned.ipa build/ios/ipa/
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - tu_email@ejemplo.com
        notify:
          success: true
          failure: true

  # Flujo de trabajo para Android
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - carolina@email.com  # Cambia esto por tu email
        notify:
          success: true
          failure: true

  # Flujo de trabajo para ambas plataformas
  all-platforms-workflow:
    name: Build All Platforms
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - carolina@email.com  # Cambia esto por tu email
        notify:
          success: true
          failure: true

